### ISSUE TITLE
Usernames with special characters mean user settings can't be accessed or updated

### ISSUE THREAD

**Issue by GingerGeek** [kubevirt-ui/kubevirt-plugin#1713]
ConfigMap keys must be confined to the regex `[-._a-zA-Z0-9]+`

Usernames in OKD/openshift can have special characters such as `@` (e.g. when provisioned through SSO, etc.)

kubevirt-user-settings is stored by username, and as such, errors occur accessing/updating settings when the logged-in user has non-confirming characters in their name.

e.g. the following request off to the API...
```
[{"op":"replace","path":"/data/me@example.com","value":"{\"quickStart\":{\"dontShowWelcomeModal\":true}}"}]
```

response
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "ConfigMap \"kubevirt-user-settings\" is invalid: data[me@example.com]: Invalid value: \"me@example.com\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')",
  "reason": "Invalid",
  "details": {
    "name": "kubevirt-user-settings",
    "kind": "ConfigMap",
    "causes": [
      {
        "reason": "FieldValueInvalid",
        "message": "Invalid value: \"me@example.com\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')",
        "field": "data[me@example.com]"
      }
    ]
  },
  "code": 422
}
```

I'm not sure if the console has access to the uid of the user object but that is alphanumeric, otherwise potentially usernames could be escaped prior to any setting operations?

**Comment by upalatucci** [comment]
Hi @GingerGeek thanks for opening the issue.

This have been fixed [here](https://github.com/kubevirt-ui/kubevirt-plugin/pull/1608). Can you please share which version you are using?

**Comment by GingerGeek** [comment]
Hi,

I use Kubevirt via the HCO deployment on OKD.

The image of the console plugin pod is `quay.io/kubevirt-ui/kubevirt-plugin@sha256:e79027973b09aac75860f267c7d7f830599978c38a081001f404b9a1c3d2990f` which is still the latest image tagged with `quay.io/kubevirt-ui/kubevirt-plugin:v4.14.0` - dated Sep 11th 2023. I can see there was a cherry pick back to the 4.14 branch, but I'm guessing this didn't seep through to the quay images and HCO operator?

Let me know if there's anything I can do to collaborate!

**Comment by upalatucci** [comment]
I think we should create a new tag on github to update the quay image with the latest 4.14 
@metalice do you think is safe to create it from the HEAD of 4.14?

**Comment by metalice** [comment]
@upalatucci yes we should

**Comment by metalice** [comment]
there is quay.io/kubevirt-ui/kubevirt-plugin:v4.14.3 - closing this issue
