### ISSUE TITLE
Cannot run cypress test with Node.js v18.19.0

### ISSUE THREAD

**Issue by gouyang** [kubevirt-ui/kubevirt-plugin#1784]
./test-cypress.sh                                                                                    
+ yarn install --ignore-engines
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @patternfly/quickstarts@2.2.4" has unmet peer dependency "showdown@>=1.8.6".
warning " > react-i18next@11.18.4" has unmet peer dependency "i18next@>= 19.0.0".
warning " > react-tagsinput@3.19.0" has incorrect peer dependency "react@^16.0.0 || ^15.0.0 || ^0.14.0".
warning " > react-use-websocket@4.3.1" has incorrect peer dependency "react@>= 18.0.0".
warning " > react-use-websocket@4.3.1" has incorrect peer dependency "react-dom@>= 18.0.0".
warning " > @cypress/webpack-preprocessor@5.12.2" has unmet peer dependency "@babel/core@^7.0.1".
warning " > @cypress/webpack-preprocessor@5.12.2" has unmet peer dependency "@babel/preset-env@^7.0.0".
warning " > @cypress/webpack-preprocessor@5.12.2" has unmet peer dependency "babel-loader@^8.0.2".
warning "@openshift-console/dynamic-plugin-sdk > @patternfly/quickstarts@2.4.0" has unmet peer dependency "showdown@>=1.8.6".
warning "@openshift-console/dynamic-plugin-sdk-internal > @patternfly/quickstarts@2.0.1" has unmet peer dependency "showdown@>=1.8.6".
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
[4/4] Building fresh packages...
$ cp node_modules/@openshift-console/dynamic-plugin-sdk/docs/console-extensions.md .
$ husky install
husky - Git hooks installed
Done in 348.46s.
+ yarn add global mochawesome-report-generator --ignore-engines
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @patternfly/quickstarts@2.2.4" has unmet peer dependency "showdown@>=1.8.6".
warning " > react-i18next@11.18.4" has unmet peer dependency "i18next@>= 19.0.0".
warning " > react-tagsinput@3.19.0" has incorrect peer dependency "react@^16.0.0 || ^15.0.0 || ^0.14.0".
warning " > react-use-websocket@4.3.1" has incorrect peer dependency "react@>= 18.0.0".
warning " > react-use-websocket@4.3.1" has incorrect peer dependency "react-dom@>= 18.0.0".
warning " > @cypress/webpack-preprocessor@5.12.2" has unmet peer dependency "@babel/core@^7.0.1".
warning " > @cypress/webpack-preprocessor@5.12.2" has unmet peer dependency "@babel/preset-env@^7.0.0".
warning " > @cypress/webpack-preprocessor@5.12.2" has unmet peer dependency "babel-loader@^8.0.2".
warning "@openshift-console/dynamic-plugin-sdk > @patternfly/quickstarts@2.4.0" has unmet peer dependency "showdown@>=1.8.6".
warning "@openshift-console/dynamic-plugin-sdk-internal > @patternfly/quickstarts@2.0.1" has unmet peer dependency "showdown@>=1.8.6".
warning " > @testing-library/user-event@13.5.0" has unmet peer dependency "@testing-library/dom@>=7.21.4".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
├─ global@4.4.0
└─ mochawesome-report-generator@6.2.0
info All dependencies
├─ global@4.4.0
└─ mochawesome-report-generator@6.2.0
$ cp node_modules/@openshift-console/dynamic-plugin-sdk/docs/console-extensions.md .
$ husky install
husky - Git hooks installed
Done in 32.09s.
+ getopts g:s: flag
+ yarn_script=test-cypress-headless
+ '[' -n '' ']'
+ '[' -n '' ']'
+ yarn run test-cypress-headless
yarn run v1.22.19
$ cd cypress && node --max-old-space-size=4096 $(npm bin)/cypress run --config-file ./cypress.json --env openshift=true --headless
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module '/home/guohua/kubevirt-plugin/cypress/Unknown'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.19.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by gouyang** [comment]
@metalice The test is okay to run with nodejs 16, but no nodejs 18, could you take a look at the issue?

**Comment by metalice** [comment]
Have u tried updating the Cypress version?

**Comment by gouyang** [comment]
@metalice The cypress version is updated to 13.3.x in my test.

**Comment by gouyang** [comment]
The issue is gone after supporting nodejs 18.
