### ISSUE TITLE
Support console extensions to VM details navigation

### ISSUE THREAD

**Issue by evanstoner** [kubevirt-ui/kubevirt-plugin#2085]
Hello, we're a Red Hat partner building some console extensions and would like to add a horizontal nav tab to the VM details page. Without the KubeVirt plugin loaded, we can do this by adding a `console.tab/horizontalNav` extension for the `VirtualMachine` kind. However, once this plugin is loaded, the nav list is loaded [from the `useVirtualMachineTabs` hook](https://github.com/kubevirt-ui/kubevirt-plugin/blob/main/src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts) so our tab does not appear.

**Comment by spadgett** [comment]
cc @tnisan @avivtur @upalatucci @pcbailey

**Comment by upalatucci** [comment]
hei @evanstoner  we fixed it here: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2092
