### ISSUE TITLE
The API version of 'Instancetype' menu needs be upgraded from v1alpha2 to v1beta1

### ISSUE THREAD

**Issue by rh-bjeon** [kubevirt-ui/kubevirt-plugin#2173]
The API version of the instancetype menu should be upgraded from v1alpha2 to v1beta1.

Currently, the instancetype menu of the kubevirt console plugin links to the following URIs...
- For VirtualMachineClusterInstancetype: 
`${console-user}/k8s/cluster/instancetype.kubevirt.io~v1alpha2~VirtualMachineClusterInstancetype`
- For VirtualMachineInstancetype: 
`${console-user}/k8s/all-namespaces/instancetype.kubevirt.io~v1alpha2~VirtualMachineInstancetype`

This causes the following two issues:
- I cannot see VirtualMachineInstancetype at all through the 'User provided' tab. ('No VirtualMachineInstanceTypes found' message)
- When I create VirtualMachineClusterInstanceTypes or VirtualMachineInstanceTypes by pressing the 'Create' button,
a deprecationWarning message box appears.

**Comment by metalice** [comment]
Hey @rh-bjeon we have updated it in latest main, will be in for 4.17
