### ISSUE TITLE
Remove `co-` based css classes from plugin

### ISSUE THREAD

**Issue by glekner** [kubevirt-ui/kubevirt-plugin#247]
`co-` and any other inherited classes are defined in the console project and can break at any time. We need to remove our dependency on them and maintain our own CSS classes for long term stability.

**Comment by glekner** [comment]
cc @yaacov @pcbailey @vojtechszocs @hstastna @metalice @upalatucci @avivtur

**Comment by hstastna** [comment]
+1 from my side
