### ISSUE TITLE
Typo: Guest agent

### ISSUE THREAD

**Issue by apinnick** [kubevirt-ui/kubevirt-plugin#764]
I think this is supposed to be "Guest agent"

https://github.com/kubevirt-ui/kubevirt-plugin/blob/639780605c3e468f677f5459df1aea3745a62a73/locales/en/plugin__kubevirt-plugin.json#L369

**Comment by apinnick** [comment]
![image](https://user-images.githubusercontent.com/31725355/185342157-194f2498-6a65-4c65-9e67-2e2f2721a6a2.png)

**Comment by avivtur** [comment]
fixed by https://github.com/kubevirt-ui/kubevirt-plugin/pull/861
/close
