### ISSUE TITLE
"Migrations information" grammatical error

### ISSUE THREAD

**Issue by apinnick** [kubevirt-ui/kubevirt-plugin#765]
This should be "Virtual machine (or VirtualMachine, which looks strange) **migration** information". 

"migration" is an adjective in this context, modifying "information". English adjectives do not have plural forms. 

https://github.com/kubevirt-ui/kubevirt-plugin/blob/639780605c3e468f677f5459df1aea3745a62a73/locales/en/plugin__kubevirt-plugin.json#L838

**Comment by avivtur** [comment]
this been changed to `"VirtualMachineInstanceMigrations information": "VirtualMachineInstanceMigrations information"` so it would fit with the resource name for VMIM, should we still remove the plural?

**Comment by apinnick** [comment]
Yes, you should remove the plural. 

"VirtualMachineInstanceMigration" is an adjective, not a noun. English adjectives do not have singular/plural forms. 
It modifies "information", which is a noun. So this should be "VirtualMachineInstanceMigration information".

**Comment by apinnick** [comment]
Fixed
